services:
  pwpa_message_bus:
    container_name: pwpa_message_bus
    image: rabbitmq:management
    hostname: 'pwpamessagebus'
    # environment: ## N/A - it initiates in definitions.json
    #   RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
    #   RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - 8005:15672
      - 8006:5672
    volumes:
      - pwpa_message_bus_vol:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - pwpa_network

volumes:
  pwpa_message_bus_vol:

networks:
  pwpa_network:
    driver: bridge
    name: pwpa_network